ad_base<-ad_base %>%   
  filter(str_detect(ADDRESS_LINE_1,"^(PROPOSED )")==F,
         str_detect(ADDRESS_LINE_1,"^(HISTORIC )")==F,
         str_detect(ADDRESS_LINE_1,"^(CARAVAN HISTORIC )")==F,
         str_detect(ADDRESS_LINE_1,"^(DELMOLISHED )")==F,
         str_detect(ADDRESS_LINE_1,"^(SITE FORMERLY KNOWN AS )")==F,
         str_detect(ADDRESS_LINE_1,"^(GARAGE )")==F,
         str_detect(ADDRESS_LINE_1,"^(PLOT)")==F,
         str_detect(ADDRESS_LINE_1,"^(LAND BETWEEN )")==F,
         str_detect(ADDRESS_LINE_1,"^(LAND REAR OF )")==F,
         str_detect(ADDRESS_LINE_1,"^(LAND PHASE)")==F,
         str_detect(ADDRESS_LINE_1,"^(LAND OPPOSITE)")==F,
         str_detect(ADDRESS_LINE_1,"^(LAND TO REAR OF)")==F,
         str_detect(ADDRESS_LINE_1,"^(LAND AND )")==F,
         str_detect(ADDRESS_LINE_1,"^(GARDEN GROUND OF )")==F,
         str_detect(ADDRESS_LINE_1,"^(TAYLOR WIMPEY SITE )")==F,
         str_detect(ADDRESS_LINE_1,"^(OCLI SITE PLOT )")==F,
         str_detect(ADDRESS_LINE_1,"^(LAND TO )")==F,
         str_detect(ADDRESS_LINE_1,"^(LAND AT )")==F,
         str_detect(ADDRESS_LINE_1,"^(LAND NORTH )")==F,
         str_detect(ADDRESS_LINE_1,"^(LAND EAST )")==F,
         str_detect(ADDRESS_LINE_1,"^(LAND WEST )")==F,
         str_detect(ADDRESS_LINE_1,"^(LAND SOUTH )")==F,
         str_detect(ADDRESS_LINE_1,"^(LAND ADJACENT )")==F,
         str_detect(ADDRESS_LINE_1,"^(LAND ADJ )")==F,
         str_detect(ADDRESS_LINE_1,"^(LAND ADJOINING )")==F,
         str_detect(ADDRESS_LINE_1,"^(PHASE )")==F,
         str_detect(ADDRESS_LINE_1,"^(PLOT )")==F,
         str_detect(ADDRESS_LINE_1,"^(DEVELOPMENT SITE )")==F,
         str_detect(ADDRESS_LINE_1,"^(SITE ADJACENT )")==F,
         str_detect(ADDRESS_LINE_1,"^(SITE TO )")==F,
         str_detect(ADDRESS_LINE_1,"^(SITE AT )")==F,
         str_detect(ADDRESS_LINE_1,"^(SITE NORTH )")==F,
         str_detect(ADDRESS_LINE_1,"^(SITE EAST )")==F,
         str_detect(ADDRESS_LINE_1,"^(SITE WEST )")==F,
         str_detect(ADDRESS_LINE_1,"^(SITE SOUTH )")==F,
         str_detect(ADDRESS_LINE_1,"^(SITE ADJACENT )")==F,
         CLASSIFICATION_DESCR!="Industrial Applicable to manufacturing, engineering, maintenance, storage / wholesale distribution and extraction sites",
         CLASSIFICATION_DESCR!="Harbour / Port / Dock / Dockyard / Slipway / Landing Stage / Pier / Jetty / Pontoon / Terminal / Berthing / Quay",
         CLASSIFICATION_DESCR!="Agricultural - Applicable to land in farm ownership and not run as a separate business enterprise",
         CLASSIFICATION_DESCR!="Airfield / Airstrip / Airport / Air Transport Infrastructure Facility",
         CLASSIFICATION_DESCR!="Car / Coach / Commercial Vehicle / Taxi Parking / Park And Ride Site",
         CLASSIFICATION_DESCR!="Cemetery / Crematorium / Graveyard. In Current Use.",
         CLASSIFICATION_DESCR!="Beach Hut (Recreational, Non-Residential Use Only)",
         CLASSIFICATION_DESCR!="Forest / Arboretum / Pinetum (Managed / Unmanaged)",
         CLASSIFICATION_DESCR!="Public Household Waste Recycling Centre (HWRC)",
         CLASSIFICATION_DESCR!="Amenity - Open areas not attracting visitors",
         CLASSIFICATION_DESCR!="Mineral Quarrying / Open Extraction / Active",
         CLASSIFICATION_DESCR!="Water / Waste Water / Sewage Treatment Works",
         CLASSIFICATION_DESCR!="Pump House / Pumping Station / Water Tower",
         CLASSIFICATION_DESCR!="Water / Waste Water / Sewage Treatment Works",
         CLASSIFICATION_DESCR!="Historic / Disused Cemetery / Graveyard",
         CLASSIFICATION_DESCR!="Water / Waste Water / Sewage Treatment Works",
         CLASSIFICATION_DESCR!="Medical / Testing / Research Laboratory",
         CLASSIFICATION_DESCR!="Water / Waste Water / Sewage Treatment Works",
         CLASSIFICATION_DESCR!="Station / Interchange / Terminal / Halt)",
         CLASSIFICATION_DESCR!="Coastguard Rescue / Lookout / Station",
         CLASSIFICATION_DESCR!="Mineral / Ore Working / Quarry / Mine",
         CLASSIFICATION_DESCR!="Incinerator / Waste Transfer Station",
         CLASSIFICATION_DESCR!="Police / Transport Police / Station",
         CLASSIFICATION_DESCR!="Public Open Space / Nature Reserve",
         CLASSIFICATION_DESCR!="Goods Freight Handling / Terminal",
         CLASSIFICATION_DESCR!="Power Station / Energy Production",
         CLASSIFICATION_DESCR!="Warehouse / Store / Storage Depot",
         CLASSIFICATION_DESCR!="Animal / Bird / Marine Sanctuary",
         CLASSIFICATION_DESCR!="Gas / Oil Storage / Distribution",
         CLASSIFICATION_DESCR!="Transport Related Infrastructure",
         CLASSIFICATION_DESCR!="Electricity Production Facility",
         CLASSIFICATION_DESCR!="Automated Teller Machine (ATM)",
         CLASSIFICATION_DESCR!="Horse Racing / Breeding Stable",
         CLASSIFICATION_DESCR!="Licensed Private Members’ Club",
         CLASSIFICATION_DESCR!="Pending Internal Investigation",
         CLASSIFICATION_DESCR!="Lock-Up Garage / Garage Court",
         CLASSIFICATION_DESCR!="Oil / Gas Extraction / Active",
         CLASSIFICATION_DESCR!="Postal Sorting / Distribution",
         CLASSIFICATION_DESCR!="Water Distribution / Pumpingraffic Information Signage",
         CLASSIFICATION_DESCR!="Water Controlling / Pumping",
         CLASSIFICATION_DESCR!="Workshop / Light Industrial",
         CLASSIFICATION_DESCR!="Central Government Service",
         CLASSIFICATION_DESCR!="Diving / Swimming Facility",
         CLASSIFICATION_DESCR!="Emergency / Rescue Service",
         CLASSIFICATION_DESCR!="Equestrian Sports Facility",
         CLASSIFICATION_DESCR!="Slaughter House / Abattoir",
         CLASSIFICATION_DESCR!="Broadcasting (TV / Radio)",
         CLASSIFICATION_DESCR!="Greyhound Racing Facility",
         CLASSIFICATION_DESCR!="Tenpin Bowling Facility",
         CLASSIFICATION_DESCR!="Castle / Historic Ruin",
         CLASSIFICATION_DESCR!="Road Freight Transport",
         CLASSIFICATION_DESCR!="Vacant / Derelict Land",
         CLASSIFICATION_DESCR!="Wholesale Distribution",
         CLASSIFICATION_DESCR!="Entertainment Complex",
         CLASSIFICATION_DESCR!="Factory/Manufacturing",
         CLASSIFICATION_DESCR!="Private Park / Garden",
         CLASSIFICATION_DESCR!="Petrol Filling Station",
         CLASSIFICATION_DESCR!="Market (Indoor / Outdoor)",
         CLASSIFICATION_DESCR!="Racquet Sports Facility",
         CLASSIFICATION_DESCR!="Bank / Financial Service",
         CLASSIFICATION_DESCR!="Memorial / Market Cross",
         CLASSIFICATION_DESCR!="Civilian Firing Facility",
         CLASSIFICATION_DESCR!="Electricity Sub-Station",
         CLASSIFICATION_DESCR!="Water Quality Monitoring")